version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: typehandler
    ports:
      - "3306:3306"